from words import words_en
word_list = words_en.words

for entry in word_list:
    for entry2 in word_list[entry]:
        if 'manual' in entry2:
            continue
        if 'block' in entry2:

            block1 = '# Attempt to fill / kill / clear in block\n'
            if not 'not_item' in entry2:
                block1+= 'execute store result score #blocks_killed1 vars run kill @e[type=minecraft:item,nbt={Item:{id:"minecraft:' + entry2['block'] + '"}}]\n'
                if not 'dont_drop' in entry2:
                    block1+= 'execute store result score #blocks_killed2 vars run kill @e[type=minecraft:falling_block,nbt={BlockState:{Name:"minecraft:' + entry2['block'] + '"}}]\n'
            elif not 'dont_drop' in entry2:
                block1 += 'execute store result score #blocks_killed1 vars run kill @e[type=minecraft:falling_block,nbt={BlockState:{Name:"minecraft:' + entry2['block'] + '"}}]\n'
            block1 += 'execute store result score #blocks_replaced1 vars run fill ~-22 0 ~-22 ~22 15 ~22 {} replace {}\n'.format('minecraft:water' if 'replace_with_water' in entry2 else 'minecraft:air', entry2['replacement_tag'] if 'replacement_tag' in entry2 else 'minecraft:' + entry2['block'])
            block1 += 'execute store result score #blocks_replaced2 vars run fill ~-22 16 ~-22 ~22 31 ~22 {} replace {}\n'.format('minecraft:water' if 'replace_with_water' in entry2 else 'minecraft:air', entry2['replacement_tag'] if 'replacement_tag' in entry2 else 'minecraft:' + entry2['block'])
            block1 += 'execute store result score #blocks_replaced3 vars run fill ~-22 32 ~-22 ~22 47 ~22 {} replace {}\n'.format('minecraft:water' if 'replace_with_water' in entry2 else 'minecraft:air', entry2['replacement_tag'] if 'replacement_tag' in entry2 else 'minecraft:' + entry2['block'])
            block1 += 'execute store result score #blocks_replaced4 vars run fill ~-22 48 ~-22 ~22 63 ~22 {} replace {}\n'.format('minecraft:water' if 'replace_with_water' in entry2 else 'minecraft:air', entry2['replacement_tag'] if 'replacement_tag' in entry2 else 'minecraft:' + entry2['block'])
            block1 += 'execute store result score #blocks_replaced5 vars run fill ~-22 64 ~-22 ~22 79 ~22 {} replace {}\n'.format('minecraft:water' if 'replace_with_water' in entry2 else 'minecraft:air', entry2['replacement_tag'] if 'replacement_tag' in entry2 else 'minecraft:' + entry2['block'])
            block1 += 'execute store result score #blocks_replaced6 vars run fill ~-22 80 ~-22 ~22 95 ~22 {} replace {}\n'.format('minecraft:water' if 'replace_with_water' in entry2 else 'minecraft:air', entry2['replacement_tag'] if 'replacement_tag' in entry2 else 'minecraft:' + entry2['block'])
            block1 += 'execute store result score #blocks_replaced7 vars run fill ~-22 96 ~-22 ~22 111 ~22 {} replace {}\n'.format('minecraft:water' if 'replace_with_water' in entry2 else 'minecraft:air', entry2['replacement_tag'] if 'replacement_tag' in entry2 else 'minecraft:' + entry2['block'])
            block1 += 'execute store result score #blocks_replaced8 vars run fill ~-22 112 ~-22 ~22 127 ~22 {} replace {}\n'.format('minecraft:water' if 'replace_with_water' in entry2 else 'minecraft:air', entry2['replacement_tag'] if 'replacement_tag' in entry2 else 'minecraft:' + entry2['block'])
            block1 += 'execute store result score #blocks_replaced9 vars run fill ~-22 128 ~-22 ~22 143 ~22 {} replace {}\n'.format('minecraft:water' if 'replace_with_water' in entry2 else 'minecraft:air', entry2['replacement_tag'] if 'replacement_tag' in entry2 else 'minecraft:' + entry2['block'])
            block1 += 'execute store result score #blocks_replaced10 vars run fill ~-22 144 ~-22 ~22 159 ~22 {} replace {}\n'.format('minecraft:water' if 'replace_with_water' in entry2 else 'minecraft:air', entry2['replacement_tag'] if 'replacement_tag' in entry2 else 'minecraft:' + entry2['block'])
            block1 += 'execute store result score #blocks_replaced11 vars run fill ~-22 160 ~-22 ~22 175 ~22 {} replace {}\n'.format('minecraft:water' if 'replace_with_water' in entry2 else 'minecraft:air', entry2['replacement_tag'] if 'replacement_tag' in entry2 else 'minecraft:' + entry2['block'])
            block1 += 'execute store result score #blocks_replaced12 vars run fill ~-22 176 ~-22 ~22 191 ~22 {} replace {}\n'.format('minecraft:water' if 'replace_with_water' in entry2 else 'minecraft:air', entry2['replacement_tag'] if 'replacement_tag' in entry2 else 'minecraft:' + entry2['block'])
            block1 += 'execute store result score #blocks_replaced13 vars run fill ~-22 192 ~-22 ~22 207 ~22 {} replace {}\n'.format('minecraft:water' if 'replace_with_water' in entry2 else 'minecraft:air', entry2['replacement_tag'] if 'replacement_tag' in entry2 else 'minecraft:' + entry2['block'])
            block1 += 'execute store result score #blocks_replaced14 vars run fill ~-22 208 ~-22 ~22 223 ~22 {} replace {}\n'.format('minecraft:water' if 'replace_with_water' in entry2 else 'minecraft:air', entry2['replacement_tag'] if 'replacement_tag' in entry2 else 'minecraft:' + entry2['block'])
            block1 += 'execute store result score #blocks_replaced15 vars run fill ~-22 224 ~-22 ~22 239 ~22 {} replace {}\n'.format('minecraft:water' if 'replace_with_water' in entry2 else 'minecraft:air', entry2['replacement_tag'] if 'replacement_tag' in entry2 else 'minecraft:' + entry2['block'])
            block1 += 'execute store result score #blocks_replaced16 vars run fill ~-22 240 ~-22 ~22 255 ~22 {} replace {}\n'.format('minecraft:water' if 'replace_with_water' in entry2 else 'minecraft:air', entry2['replacement_tag'] if 'replacement_tag' in entry2 else 'minecraft:' + entry2['block'])
            if 'potted_version' in entry2:
                block1 += 'execute store result score #blocks_replaced17 vars run fill ~-22 0 ~-22 ~22 15 ~22 flower_pot replace minecraft:potted_{}\n'.format(entry2['block'])
                block1 += 'execute store result score #blocks_replaced18 vars run fill ~-22 16 ~-22 ~22 31 ~22 flower_pot replace minecraft:potted_{}\n'.format(entry2['block'])
                block1 += 'execute store result score #blocks_replaced19 vars run fill ~-22 32 ~-22 ~22 47 ~22 flower_pot replace minecraft:potted_{}\n'.format(entry2['block'])
                block1 += 'execute store result score #blocks_replaced20 vars run fill ~-22 48 ~-22 ~22 63 ~22 flower_pot replace minecraft:potted_{}\n'.format(entry2['block'])
                block1 += 'execute store result score #blocks_replaced21 vars run fill ~-22 64 ~-22 ~22 79 ~22 flower_pot replace minecraft:potted_{}\n'.format(entry2['block'])
                block1 += 'execute store result score #blocks_replaced22 vars run fill ~-22 80 ~-22 ~22 95 ~22 flower_pot replace minecraft:potted_{}\n'.format(entry2['block'])
                block1 += 'execute store result score #blocks_replaced23 vars run fill ~-22 96 ~-22 ~22 111 ~22 flower_pot replace minecraft:potted_{}\n'.format(entry2['block'])
                block1 += 'execute store result score #blocks_replaced24 vars run fill ~-22 112 ~-22 ~22 127 ~22 flower_pot replace minecraft:potted_{}\n'.format(entry2['block'])
                block1 += 'execute store result score #blocks_replaced25 vars run fill ~-22 128 ~-22 ~22 143 ~22 flower_pot replace minecraft:potted_{}\n'.format(entry2['block'])
                block1 += 'execute store result score #blocks_replaced26 vars run fill ~-22 144 ~-22 ~22 159 ~22 flower_pot replace minecraft:potted_{}\n'.format(entry2['block'])
                block1 += 'execute store result score #blocks_replaced27 vars run fill ~-22 160 ~-22 ~22 175 ~22 flower_pot replace minecraft:potted_{}\n'.format(entry2['block'])
                block1 += 'execute store result score #blocks_replaced28 vars run fill ~-22 176 ~-22 ~22 191 ~22 flower_pot replace minecraft:potted_{}\n'.format(entry2['block'])
                block1 += 'execute store result score #blocks_replaced29 vars run fill ~-22 192 ~-22 ~22 207 ~22 flower_pot replace minecraft:potted_{}\n'.format(entry2['block'])
                block1 += 'execute store result score #blocks_replaced30 vars run fill ~-22 208 ~-22 ~22 223 ~22 flower_pot replace minecraft:potted_{}\n'.format(entry2['block'])
                block1 += 'execute store result score #blocks_replaced31 vars run fill ~-22 224 ~-22 ~22 239 ~22 flower_pot replace minecraft:potted_{}\n'.format(entry2['block'])
                block1 += 'execute store result score #blocks_replaced32 vars run fill ~-22 240 ~-22 ~22 255 ~22 flower_pot replace minecraft:potted_{}\n'.format(entry2['block'])
                potted_checks = 'if score #blocks_replaced17 vars matches 0 if score #blocks_replaced18 vars matches 0 if score #blocks_replaced19 vars matches 0 if score #blocks_replaced20 vars matches 0 if score #blocks_replaced21 vars matches 0 if score #blocks_replaced22 vars matches 0 if score #blocks_replaced23 vars matches 0 if score #blocks_replaced24 vars matches 0 if score #blocks_replaced25 vars matches 0 if score #blocks_replaced26 vars matches 0 if score #blocks_replaced27 vars matches 0 if score #blocks_replaced28 vars matches 0 if score #blocks_replaced29 vars matches 0 if score #blocks_replaced30 vars matches 0 if score #blocks_replaced31 vars matches 0 if score #blocks_replaced32 vars matches 0 '
            else:
                potted_checks = ''
            if not 'not_item' in entry2:
                block1 += 'execute store result score #blocks_cleared vars run clear @a minecraft:{}\n\n'.format(entry2['block'])
            block1 += '# If block not replaced, summon some\n'
            if 'drop_as_item' in entry2:
                block1 += 'scoreboard players operation #curr_item_spawning_density vars = #item_spawning_density vars\n'
            else:
                block1 += 'scoreboard players operation #curr_block_spawning_density vars = #block_spawning_density vars\n'
            if 'not_item' in entry2:
                if 'dont_drop' in entry2:
                    block1 += 'execute if score #blocks_replaced1 vars matches 0 if score #blocks_replaced2 vars matches 0 if score #blocks_replaced3 vars matches 0 if score #blocks_replaced4 vars matches 0 if score #blocks_replaced5 vars matches 0 if score #blocks_replaced6 vars matches 0 if score #blocks_replaced7 vars matches 0 if score #blocks_replaced8 vars matches 0 if score #blocks_replaced9 vars matches 0 if score #blocks_replaced10 vars matches 0 if score #blocks_replaced11 vars matches 0 if score #blocks_replaced12 vars matches 0 if score #blocks_replaced13 vars matches 0 if score #blocks_replaced14 vars matches 0 if score #blocks_replaced15 vars matches 0 if score #blocks_replaced16 vars matches 0 {}run schedule function wordsmith:detect/block/{}2 1t'.format(potted_checks, entry2['block'])
                else:
                    block1 += 'execute if score #blocks_killed1 vars matches 0 if score #blocks_replaced1 vars matches 0 if score #blocks_replaced2 vars matches 0 if score #blocks_replaced3 vars matches 0 if score #blocks_replaced4 vars matches 0 if score #blocks_replaced5 vars matches 0 if score #blocks_replaced6 vars matches 0 if score #blocks_replaced7 vars matches 0 if score #blocks_replaced8 vars matches 0 if score #blocks_replaced9 vars matches 0 if score #blocks_replaced10 vars matches 0 if score #blocks_replaced11 vars matches 0 if score #blocks_replaced12 vars matches 0 if score #blocks_replaced13 vars matches 0 if score #blocks_replaced14 vars matches 0 if score #blocks_replaced15 vars matches 0 if score #blocks_replaced16 vars matches 0 {}run schedule function wordsmith:detect/block/{}2 1t'.format(potted_checks, entry2['block'])
            elif 'dont_drop' in entry2:
                block1 += 'execute if score #blocks_killed1 vars matches 0 if score #blocks_replaced1 vars matches 0 if score #blocks_replaced2 vars matches 0 if score #blocks_replaced3 vars matches 0 if score #blocks_replaced4 vars matches 0 if score #blocks_replaced5 vars matches 0 if score #blocks_replaced6 vars matches 0 if score #blocks_replaced7 vars matches 0 if score #blocks_replaced8 vars matches 0 if score #blocks_replaced9 vars matches 0 if score #blocks_replaced10 vars matches 0 if score #blocks_replaced11 vars matches 0 if score #blocks_replaced12 vars matches 0 if score #blocks_replaced13 vars matches 0 if score #blocks_replaced14 vars matches 0 if score #blocks_replaced15 vars matches 0 if score #blocks_replaced16 vars matches 0 {}if score #blocks_cleared vars matches 0 run schedule function wordsmith:detect/block/{}2 1t'.format(potted_checks, entry2['block'])
            else:
                block1 += 'execute if score #blocks_killed1 vars matches 0 if score #blocks_killed2 vars matches 0 if score #blocks_replaced1 vars matches 0 if score #blocks_replaced2 vars matches 0 if score #blocks_replaced3 vars matches 0 if score #blocks_replaced4 vars matches 0 if score #blocks_replaced5 vars matches 0 if score #blocks_replaced6 vars matches 0 if score #blocks_replaced7 vars matches 0 if score #blocks_replaced8 vars matches 0 if score #blocks_replaced9 vars matches 0 if score #blocks_replaced10 vars matches 0 if score #blocks_replaced11 vars matches 0 if score #blocks_replaced12 vars matches 0 if score #blocks_replaced13 vars matches 0 if score #blocks_replaced14 vars matches 0 if score #blocks_replaced15 vars matches 0 if score #blocks_replaced16 vars matches 0 {}if score #blocks_cleared vars matches 0 run schedule function wordsmith:detect/block/{}2 1t'.format(potted_checks, entry2['block'])

            block2 = ''
            if 'dont_drop' in entry2 or 'drop_once' in entry2 or 'density' in entry2 or 'double' in entry2:
                ratio = 1.
                if 'density' in entry2:
                    ratio = float(entry2['density'])
                if 'dont_drop' in entry2 or 'drop_once' in entry2 or 'double' in entry2:
                    ratio *= 2
                if ratio != 1.:
                    block2 += '# Set block density ({}x)\n'.format(ratio)
                    ratio2 = ratio.as_integer_ratio()
                    if ratio2[0] != 1:
                        block2 += 'scoreboard players set #temp vars {}\n'.format(ratio2[0])
                        block2 += 'scoreboard players operation #curr_block_spawning_density vars *= #temp vars\n'
                    if ratio2[1] != 1:
                        block2 += 'scoreboard players set #temp vars {}\n'.format(ratio2[0])
                        block2 += 'scoreboard players operation #curr_block_spawning_density vars /= #temp vars\n'
                    if ratio < 1:
                        block2 += 'execute if score #curr_block_spawning_density vars matches 0 run scoreboard players set #curr_block_spawning_density vars 1'
                    block2 += '\n'
            block2 += '# Summon armor stands\n'
            if 'drop_as_item' in entry2:
                block2 += 'scoreboard players operation #spreaded_armor_stands vars = #curr_item_spawning_density vars\n'
            else:
                block2 += 'scoreboard players operation #spreaded_armor_stands vars = #curr_block_spawning_density vars\n'
            block2 += 'function wordsmith:detect/spread_armor_stands_r1\n\n'
            if 'drop_as_item' in entry2:
                block2 += '# Summon block\n'
                block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner] run summon item ~ ~10 ~ {Item:{id:"minecraft:' + entry2['block'] + '",Count:1b}}\n'
                block2 += '\n# Give fancy particle for the current team'
                block2 += '\nexecute if score #team_turn vars matches 0 at @e[type=minecraft:armor_stand,tag=spawner] run particle minecraft:dust 1 0.1 0.1 1 ~ ~10 ~ 0.3 0.3 0.3 1 30'
                block2 += '\nexecute if score #team_turn vars matches 1 at @e[type=minecraft:armor_stand,tag=spawner] run particle minecraft:dust 0.2 0.2 1 1 ~ ~10 ~ 0.3 0.3 0.3 1 30'
                block2 += '\nexecute if score #team_turn vars matches 2 at @e[type=minecraft:armor_stand,tag=spawner] run particle minecraft:dust 0.2 1 0.2 1 ~ ~10 ~ 0.3 0.3 0.3 1 30'
                block2 += '\nexecute if score #team_turn vars matches 3 at @e[type=minecraft:armor_stand,tag=spawner] run particle minecraft:dust 1 1 0.1 1 ~ ~10 ~ 0.3 0.3 0.3 1 30'
            elif 'directional_tag' in entry2:
                block2 += '# Get RNG roll for block orientation\n'
                block2 += 'scoreboard players set @e[type=minecraft:armor_stand,tag=spawner] jrngMin 0\n'
                if entry2['directional_tag'] == 'axis':
                    block2 += 'scoreboard players set @e[type=minecraft:armor_stand,tag=spawner] jrngMax 3\n'
                elif entry2['directional_tag'] == 'facing':
                    block2 += 'scoreboard players set @e[type=minecraft:armor_stand,tag=spawner] jrngMax 4\n'
                elif entry2['directional_tag'] == 'facing2':
                    block2 += 'scoreboard players set @e[type=minecraft:armor_stand,tag=spawner] jrngMax 5\n'
                elif entry2['directional_tag'] == 'shape':
                    block2 += 'scoreboard players set @e[type=minecraft:armor_stand,tag=spawner] jrngMax 2\n'
                elif entry2['directional_tag'] == 'rotation':
                    block2 += 'scoreboard players set @e[type=minecraft:armor_stand,tag=spawner] jrngMax 16\n'
                block2 += 'execute as @e[type=minecraft:armor_stand,tag=spawner] run function jrng:roll\n\n'
                block2 += '# Summon block\n'
                if 'dont_drop' in entry2:
                    if entry2['directional_tag'] == 'axis':
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=0}] run setblock ~ ~ ~ minecraft:' + entry2['block'] + '[axis=x' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace('}', ']').replace(' ', '').replace(':', '=').replace('{', '') + '' if 'required_tag' in entry2 else ']') + (entry2['required_nbt'] if 'required_nbt' in entry2 else '') + '\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=1}] run setblock ~ ~ ~ minecraft:' + entry2['block'] + '[axis=y' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace('}', ']').replace(' ', '').replace(':', '=').replace('{', '') + '' if 'required_tag' in entry2 else ']') + (entry2['required_nbt'] if 'required_nbt' in entry2 else '') + '\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=2}] run setblock ~ ~ ~ minecraft:' + entry2['block'] + '[axis=z' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace('}', ']').replace(' ', '').replace(':', '=').replace('{', '') + '' if 'required_tag' in entry2 else ']') + (entry2['required_nbt'] if 'required_nbt' in entry2 else '') + '\n'
                    elif entry2['directional_tag'] == 'facing':
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=0}] run setblock ~ ~ ~ minecraft:' + entry2['block'] + '[facing=north' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace('}', ']').replace(' ', '').replace(':', '=').replace('{', '') + '' if 'required_tag' in entry2 else ']') + (entry2['required_nbt'] if 'required_nbt' in entry2 else '') + '\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=1}] run setblock ~ ~ ~ minecraft:' + entry2['block'] + '[facing=east' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace('}', ']').replace(' ', '').replace(':', '=').replace('{', '') + '' if 'required_tag' in entry2 else ']') + (entry2['required_nbt'] if 'required_nbt' in entry2 else '') + '\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=2}] run setblock ~ ~ ~ minecraft:' + entry2['block'] + '[facing=south' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace('}', ']').replace(' ', '').replace(':', '=').replace('{', '') + '' if 'required_tag' in entry2 else ']') + (entry2['required_nbt'] if 'required_nbt' in entry2 else '') + '\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=3}] run setblock ~ ~ ~ minecraft:' + entry2['block'] + '[facing=west' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace('}', ']').replace(' ', '').replace(':', '=').replace('{', '') + '' if 'required_tag' in entry2 else ']') + (entry2['required_nbt'] if 'required_nbt' in entry2 else '') + '\n'
                    elif entry2['directional_tag'] == 'facing2':
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=0}] run setblock ~ ~ ~ minecraft:' + entry2['block'] + '[facing=north' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace('}', ']').replace(' ', '').replace(':', '=').replace('{', '') + '' if 'required_tag' in entry2 else ']') + (entry2['required_nbt'] if 'required_nbt' in entry2 else '') + '\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=1}] run setblock ~ ~ ~ minecraft:' + entry2['block'] + '[facing=east' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace('}', ']').replace(' ', '').replace(':', '=').replace('{', '') + '' if 'required_tag' in entry2 else ']') + (entry2['required_nbt'] if 'required_nbt' in entry2 else '') + '\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=2}] run setblock ~ ~ ~ minecraft:' + entry2['block'] + '[facing=south' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace('}', ']').replace(' ', '').replace(':', '=').replace('{', '') + '' if 'required_tag' in entry2 else ']') + (entry2['required_nbt'] if 'required_nbt' in entry2 else '') + '\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=3}] run setblock ~ ~ ~ minecraft:' + entry2['block'] + '[facing=west' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace('}', ']').replace(' ', '').replace(':', '=').replace('{', '') + '' if 'required_tag' in entry2 else ']') + (entry2['required_nbt'] if 'required_nbt' in entry2 else '') + '\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=4}] run setblock ~ ~ ~ minecraft:' + entry2['block'] + '[facing=up' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace('}', ']').replace(' ', '').replace(':', '=').replace('{', '') + '' if 'required_tag' in entry2 else ']') + (entry2['required_nbt'] if 'required_nbt' in entry2 else '') + '\n'
                    elif entry2['directional_tag'] == 'shape':
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=0}] run setblock ~ ~ ~ minecraft:' + entry2['block'] + '[shape=east_west' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace('}', ']').replace(' ', '').replace(':', '=').replace('{', '') + '' if 'required_tag' in entry2 else ']') + (entry2['required_nbt'] if 'required_nbt' in entry2 else '') + '\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=1}] run setblock ~ ~ ~ minecraft:' + entry2['block'] + '[shape=north_south' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace('}', ']').replace(' ', '').replace(':', '=').replace('{', '') + '' if 'required_tag' in entry2 else ']') + (entry2['required_nbt'] if 'required_nbt' in entry2 else '') + '\n'
                    elif entry2['directional_tag'] == 'rotation':
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=0}] run setblock ~ ~ ~ minecraft:' + entry2['block'] + '[rotation=0' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace('}', ']').replace(' ', '').replace(':', '=').replace('{', '') + '' if 'required_tag' in entry2 else ']') + (entry2['required_nbt'] if 'required_nbt' in entry2 else '') + '\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=1}] run setblock ~ ~ ~ minecraft:' + entry2['block'] + '[rotation=1' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace('}', ']').replace(' ', '').replace(':', '=').replace('{', '') + '' if 'required_tag' in entry2 else ']') + (entry2['required_nbt'] if 'required_nbt' in entry2 else '') + '\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=2}] run setblock ~ ~ ~ minecraft:' + entry2['block'] + '[rotation=2' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace('}', ']').replace(' ', '').replace(':', '=').replace('{', '') + '' if 'required_tag' in entry2 else ']') + (entry2['required_nbt'] if 'required_nbt' in entry2 else '') + '\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=3}] run setblock ~ ~ ~ minecraft:' + entry2['block'] + '[rotation=3' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace('}', ']').replace(' ', '').replace(':', '=').replace('{', '') + '' if 'required_tag' in entry2 else ']') + (entry2['required_nbt'] if 'required_nbt' in entry2 else '') + '\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=4}] run setblock ~ ~ ~ minecraft:' + entry2['block'] + '[rotation=4' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace('}', ']').replace(' ', '').replace(':', '=').replace('{', '') + '' if 'required_tag' in entry2 else ']') + (entry2['required_nbt'] if 'required_nbt' in entry2 else '') + '\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=5}] run setblock ~ ~ ~ minecraft:' + entry2['block'] + '[rotation=5' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace('}', ']').replace(' ', '').replace(':', '=').replace('{', '') + '' if 'required_tag' in entry2 else ']') + (entry2['required_nbt'] if 'required_nbt' in entry2 else '') + '\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=6}] run setblock ~ ~ ~ minecraft:' + entry2['block'] + '[rotation=6' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace('}', ']').replace(' ', '').replace(':', '=').replace('{', '') + '' if 'required_tag' in entry2 else ']') + (entry2['required_nbt'] if 'required_nbt' in entry2 else '') + '\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=7}] run setblock ~ ~ ~ minecraft:' + entry2['block'] + '[rotation=7' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace('}', ']').replace(' ', '').replace(':', '=').replace('{', '') + '' if 'required_tag' in entry2 else ']') + (entry2['required_nbt'] if 'required_nbt' in entry2 else '') + '\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=8}] run setblock ~ ~ ~ minecraft:' + entry2['block'] + '[rotation=8' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace('}', ']').replace(' ', '').replace(':', '=').replace('{', '') + '' if 'required_tag' in entry2 else ']') + (entry2['required_nbt'] if 'required_nbt' in entry2 else '') + '\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=9}] run setblock ~ ~ ~ minecraft:' + entry2['block'] + '[rotation=9' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace('}', ']').replace(' ', '').replace(':', '=').replace('{', '') + '' if 'required_tag' in entry2 else ']') + (entry2['required_nbt'] if 'required_nbt' in entry2 else '') + '\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=10}] run setblock ~ ~ ~ minecraft:' + entry2['block'] + '[rotation=10' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace('}', ']').replace(' ', '').replace(':', '=').replace('{', '') + '' if 'required_tag' in entry2 else ']') + (entry2['required_nbt'] if 'required_nbt' in entry2 else '') + '\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=11}] run setblock ~ ~ ~ minecraft:' + entry2['block'] + '[rotation=11' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace('}', ']').replace(' ', '').replace(':', '=').replace('{', '') + '' if 'required_tag' in entry2 else ']') + (entry2['required_nbt'] if 'required_nbt' in entry2 else '') + '\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=12}] run setblock ~ ~ ~ minecraft:' + entry2['block'] + '[rotation=12' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace('}', ']').replace(' ', '').replace(':', '=').replace('{', '') + '' if 'required_tag' in entry2 else ']') + (entry2['required_nbt'] if 'required_nbt' in entry2 else '') + '\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=13}] run setblock ~ ~ ~ minecraft:' + entry2['block'] + '[rotation=13' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace('}', ']').replace(' ', '').replace(':', '=').replace('{', '') + '' if 'required_tag' in entry2 else ']') + (entry2['required_nbt'] if 'required_nbt' in entry2 else '') + '\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=14}] run setblock ~ ~ ~ minecraft:' + entry2['block'] + '[rotation=14' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace('}', ']').replace(' ', '').replace(':', '=').replace('{', '') + '' if 'required_tag' in entry2 else ']') + (entry2['required_nbt'] if 'required_nbt' in entry2 else '') + '\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=15}] run setblock ~ ~ ~ minecraft:' + entry2['block'] + '[rotation=15' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace('}', ']').replace(' ', '').replace(':', '=').replace('{', '') + '' if 'required_tag' in entry2 else ']') + (entry2['required_nbt'] if 'required_nbt' in entry2 else '') + '\n'
                    block2 += '\n# Give fancy particle for the current team'
                    block2 += '\nexecute if score #team_turn vars matches 0 at @e[type=minecraft:armor_stand,tag=spawner] run particle minecraft:dust 1 0.1 0.1 1 ~ ~0 ~ 0.6 0.6 0.6 1 60'
                    block2 += '\nexecute if score #team_turn vars matches 1 at @e[type=minecraft:armor_stand,tag=spawner] run particle minecraft:dust 0.2 0.2 1 1 ~ ~0 ~ 0.6 0.6 0.6 1 60'
                    block2 += '\nexecute if score #team_turn vars matches 2 at @e[type=minecraft:armor_stand,tag=spawner] run particle minecraft:dust 0.2 1 0.2 1 ~ ~0 ~ 0.6 0.6 0.6 1 60'
                    block2 += '\nexecute if score #team_turn vars matches 3 at @e[type=minecraft:armor_stand,tag=spawner] run particle minecraft:dust 1 1 0.1 1 ~ ~0 ~ 0.6 0.6 0.6 1 60'
                else:
                    if entry2['directional_tag'] == 'axis':
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=0}] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{axis:"x"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=1}] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{axis:"y"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=2}] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{axis:"z"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                    if entry2['directional_tag'] == 'facing':
                        if 'double' in entry2:
                            block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=0}] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{facing:"north",half:"lower"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                            block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=0}] run summon falling_block ~ ~11 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{facing:"north",half:"upper"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                            block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=1}] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{facing:"east",half:"lower"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                            block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=1}] run summon falling_block ~ ~11 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{facing:"east",half:"upper"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                            block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=2}] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{facing:"south",half:"lower"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                            block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=2}] run summon falling_block ~ ~11 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{facing:"south",half:"upper"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                            block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=3}] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{facing:"west",half:"lower"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                            block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=3}] run summon falling_block ~ ~11 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{facing:"west",half:"upper"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                        else:
                            block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=0}] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{facing:"north"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                            block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=1}] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{facing:"east"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                            block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=2}] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{facing:"south"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                            block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=3}] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{facing:"west"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                    if entry2['directional_tag'] == 'facing2':
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=0}] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{facing:"north"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=1}] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{facing:"east"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=2}] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{facing:"south"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=3}] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{facing:"west"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=4}] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{facing:"up"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                    if entry2['directional_tag'] == 'shape':
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=0}] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{shape:"east_west"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=1}] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{shape:"north_south"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                    if entry2['directional_tag'] == 'rotation':
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=0}] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{rotation:"0"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=1}] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{rotation:"1"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=2}] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{rotation:"2"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=3}] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{rotation:"3"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=4}] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{rotation:"4"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=5}] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{rotation:"5"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=6}] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{rotation:"6"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=7}] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{rotation:"7"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=8}] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{rotation:"8"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=9}] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{rotation:"9"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=10}] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{rotation:"10"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=11}] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{rotation:"11"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=12}] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{rotation:"12"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=13}] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{rotation:"13"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=14}] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{rotation:"14"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                        block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner,scores={jrngResult=15}] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + ',Properties:{rotation:"15"' + (',' + str(entry2['required_tag']).replace('{', '').replace('\'', '').replace(':', ':"').replace('}', '"}').replace(' ', '') if 'required_tag' in entry2 else '}') + '},Time:1}\n'
                    block2 += '\n# Give fancy particle for the current team'
                    block2 += '\nexecute if score #team_turn vars matches 0 at @e[type=minecraft:armor_stand,tag=spawner] run particle minecraft:dust 1 0.1 0.1 1 ~ ~10 ~ 0.6 0.6 0.6 1 60'
                    block2 += '\nexecute if score #team_turn vars matches 1 at @e[type=minecraft:armor_stand,tag=spawner] run particle minecraft:dust 0.2 0.2 1 1 ~ ~10 ~ 0.6 0.6 0.6 1 60'
                    block2 += '\nexecute if score #team_turn vars matches 2 at @e[type=minecraft:armor_stand,tag=spawner] run particle minecraft:dust 0.2 1 0.2 1 ~ ~10 ~ 0.6 0.6 0.6 1 60'
                    block2 += '\nexecute if score #team_turn vars matches 3 at @e[type=minecraft:armor_stand,tag=spawner] run particle minecraft:dust 1 1 0.1 1 ~ ~10 ~ 0.6 0.6 0.6 1 60'
            else:
                block2 += '# Summon block\n'
                if 'dont_drop' in entry2:
                    block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner] run setblock ~ ~ ~ minecraft:{}'.format(entry2['block']) + (str(entry2['required_tag']).replace('{', '[').replace('\'', '').replace('}', ']').replace(' ', '').replace(':', '=') + '\n' if 'required_tag' in entry2 else '\n')
                    block2 += '\n# Give fancy particle for the current team'
                    block2 += '\nexecute if score #team_turn vars matches 0 at @e[type=minecraft:armor_stand,tag=spawner] run particle minecraft:dust 1 0.1 0.1 1 ~ ~0 ~ 0.6 0.6 0.6 1 60'
                    block2 += '\nexecute if score #team_turn vars matches 1 at @e[type=minecraft:armor_stand,tag=spawner] run particle minecraft:dust 0.2 0.2 1 1 ~ ~0 ~ 0.6 0.6 0.6 1 60'
                    block2 += '\nexecute if score #team_turn vars matches 2 at @e[type=minecraft:armor_stand,tag=spawner] run particle minecraft:dust 0.2 1 0.2 1 ~ ~0 ~ 0.6 0.6 0.6 1 60'
                    block2 += '\nexecute if score #team_turn vars matches 3 at @e[type=minecraft:armor_stand,tag=spawner] run particle minecraft:dust 1 1 0.1 1 ~ ~0 ~ 0.6 0.6 0.6 1 60'
                else:
                    block2 += 'execute at @e[type=minecraft:armor_stand,tag=spawner] run summon falling_block ~ ~10 ~ {BlockState:{Name:"minecraft:' + entry2['block'] + '"' + (',Properties:' + str(entry2['required_tag']).replace('\'', '').replace(':', ':"').replace('}', '"}').replace(',', '",').replace(' ', '') if 'required_tag' in entry2 else '') + '},Time:1}\n'
                    block2 += '\n# Give fancy particle for the current team'
                    block2 += '\nexecute if score #team_turn vars matches 0 at @e[type=minecraft:armor_stand,tag=spawner] run particle minecraft:dust 1 0.1 0.1 1 ~ ~10 ~ 0.6 0.6 0.6 1 60'
                    block2 += '\nexecute if score #team_turn vars matches 1 at @e[type=minecraft:armor_stand,tag=spawner] run particle minecraft:dust 0.2 0.2 1 1 ~ ~10 ~ 0.6 0.6 0.6 1 60'
                    block2 += '\nexecute if score #team_turn vars matches 2 at @e[type=minecraft:armor_stand,tag=spawner] run particle minecraft:dust 0.2 1 0.2 1 ~ ~10 ~ 0.6 0.6 0.6 1 60'
                    block2 += '\nexecute if score #team_turn vars matches 3 at @e[type=minecraft:armor_stand,tag=spawner] run particle minecraft:dust 1 1 0.1 1 ~ ~10 ~ 0.6 0.6 0.6 1 60'
            block2 += '\n\n# Kill the armor stands'
            block2 += '\nkill @e[type=minecraft:armor_stand,tag=spawner]'
            if not 'dont_drop' in entry2 and not 'drop_once' in entry2 and not 'double' in entry2:
                block2 += '\n\n# Do all of that again\n' + block2.replace('~10', '~12')

            rb = open('C:/Users/popki/AppData/Roaming/.minecraft/saves/Wordsmith/datapacks/Wordsmith/data/wordsmith/functions/detect/block/{}.mcfunction'.format(entry2['block']), 'w')
            rb.write(block1)
            rb.close()

            rb = open('C:/Users/popki/AppData/Roaming/.minecraft/saves/Wordsmith/datapacks/Wordsmith/data/wordsmith/functions/detect/block/{}2.mcfunction'.format(entry2['block']), 'w')
            rb.write(block2)
            rb.close()